services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag-app:local
    container_name: rag-app
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./kb_store:/app/kb_store
